### ISSUE TITLE
Doesn't work with `@electric-sql/pglite` versions `0.2` and later

### ISSUE THREAD

**Issue by tonyfromundefined** [kamilogorek/pglite-server#3]
- I have confirmed that the current `pglite-server` does not work with `@electric-sql/pglite` versions `0.2` and higher.
- You can easily reproduce this issue by updating `@electric-sql/pglite` to the latest version in the `pglite-server` repository and then running `test/main.ts`.

I would appreciate it if you could check it out.

**Comment by tonyfromundefined** [comment]
Oh, I found this in README.md. I found this guide:

https://github.com/supabase-community/pg-gateway?tab=readme-ov-file#pglite

**Comment by kamilogorek** [comment]
You are correct. The work has been moved to more "official" Supabase channel :)
I'll archive this repo to not make it confusing. Cheers!

**Comment by kamilogorek** [comment]
Support for latest version is fixed and released as `0.1.4`.
